steps:
  - label: "step-1"
    command: |
      pip install loremipsum
      python -c "import loremipsum; sentence = loremipsum.sentence(max_char=20); print(sentence); open('result.txt', 'w').write(sentence)"
    plugins:
      - docker#v3.9.0:
          image: "python:3.13"
          volumes:
            - /tmp/assessment:/container/path

  - label: "annotate-with-result-from-result-txt"
    command: |
      buildkite-agent annotate --file result.txt
    depends_on: "step-1"
    plugins:
      - docker#v3.9.0:
          image: "python:3.13"

  - label: "run-loremipsum-paragraph-and-annotate"
    command: |
      pip install loremipsum
      python -c "import loremipsum; paragraph = loremipsum.paragraph(max_char=100); print(paragraph); open('result_paragraph.txt', 'w').write(paragraph)"
    depends_on: "annotate-with-result-from-result-txt"
    plugins:
      - docker#v3.9.0:
          image: "python:3.13"

  - label: "annotate-with-paragraph-result"
    command: |
      buildkite-agent annotate --file result_paragraph.txt
    depends_on: "run-loremipsum-paragraph-and-annotate"
    plugins:
      - docker#v3.9.0:
          image: "python:3.13"
