steps:
  - label: "step-1"
    key: "step-1"
    command: |
      pip install loremipsum
      python -c "import loremipsum; sentence = loremipsum.sentence(max_char=20); print(sentence); open('result.txt', 'w').write(sentence)"
    plugins:
      - docker#v3.9.0:
          image: "python:3.13"
          volumes:
            - /tmp/assessment:/container/path
          mount-buildkite-agent: true
    artifact_paths: "result.txt"

  - label: "annotate-with-result-from-result-txt"
    key: "step-2"
    command: |
      buildkite-agent artifact download "result.txt" .
      cat result.txt | buildkite-agent annotate --style "success"
    depends_on: "step-1"

  - label: "run-loremipsum-paragraph-and-annotate"
    key: "step-3"
    command: |
      pip install loremipsum
      python -c "import loremipsum; paragraph = loremipsum.paragraph(max_char=100); print(paragraph); open('result_paragraph.txt', 'w').write(paragraph)"
    depends_on: "step-2"
    plugins:
      - docker#v3.9.0:
          image: "python:3.13"
    artifact_paths: "result_paragraph.txt"

  - label: "annotate-with-paragraph-result"
    command: |
      buildkite-agent artifact download "result_paragraph.txt" .
      cat result_paragraph.txt | buildkite-agent annotate --style "success"
    depends_on: "step-3"
